# Generated by Django 2.1.5 on 2019-02-13 10:28

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190213_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/static/blog/img/'), upload_to=''),
        ),
    ]
