# Generated by Django 2.1.5 on 2019-02-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190213_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='excerpt',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='modified_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='writer',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
