# Generated by Django 2.1.5 on 2019-02-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190216_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='douban_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_data',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watch_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
